import requests
import re
from bs4 import BeautifulSoup, ResultSet, Tag

# from html.parser import HTMLParser

currencies = {
    # None:{'country':'ANTÁRTICA','currency':'Nenhuma moeda universal','cod':None,'number':None,'symbol':None},
    # None:{'country':'PALESTINA','currency':'Nenhuma moeda universal','cod':None,'number':None,'symbol':None},
    # None:{'country':'GEÓRGIA DO SUL E AS ILHAS SANDWICH','currency':'Nenhuma moeda universal','cod':None,'number':None,'symbol':None},
    'AFN': {'country': 'AFEGANISTÃO', 'currency': 'Afghani', 'cod': 'AFN', 'number': '971', 'symbol': 'AFN$'},
    'EUR': {'country': 'ILHAS DE ÅLAND', 'currency': 'Euro', 'cod': 'EUR', 'number': '978', 'symbol': 'EUR$'},
    'ALL': {'country': 'ALBANIA', 'currency': 'Lek', 'cod': 'ALL', 'number': '008', 'symbol': 'ALL$'},
    'DZD': {'country': 'ARGÉLIA', 'currency': 'Dinar argelino', 'cod': 'DZD', 'number': '012', 'symbol': 'DZD$'},
    # 'USD':{'country':'SAMOA AMERICANA','currency':'Dólar americano','cod':'USD','number':'840','symbol':'US$'},
    'EUR': {'country': 'ANDORRA', 'currency': 'Euro', 'cod': 'EUR', 'number': '978', 'symbol': 'EUR$'},
    'AOA': {'country': 'ANGOLA', 'currency': 'Kwanza', 'cod': 'AOA', 'number': '973', 'symbol': 'AOA$'},
    'XCD': {'country': 'ANGUILA', 'currency': 'Dólar do Caribe Oriental', 'cod': 'XCD', 'number': '951', 'symbol': 'XCD$'},
    'XCD': {'country': 'ANTÍGUA E BARBUDA', 'currency': 'Dólar do Caribe Oriental', 'cod': 'XCD', 'number': '951', 'symbol': 'XCD$'},
    'ARS': {'country': 'ARGENTINA', 'currency': 'Peso argentino', 'cod': 'ARS', 'number': '032', 'symbol': 'ARS$'},
    'AMD': {'country': 'ARMÊNIA', 'currency': 'Dram armênio', 'cod': 'AMD', 'number': '051', 'symbol': 'AMD$'},
    'AWG': {'country': 'ARUBA', 'currency': 'Florim de Aruba', 'cod': 'AWG', 'number': '533', 'symbol': 'AWG$'},
    'AUD': {'country': 'AUSTRÁLIA', 'currency': 'Dólar australiano', 'cod': 'AUD', 'number': '036', 'symbol': 'AUD$'},
    'EUR': {'country': 'ÁUSTRIA', 'currency': 'Euro', 'cod': 'EUR', 'number': '978', 'symbol': 'EUR$'},
    'AZN': {'country': 'AZERBAIJÃO', 'currency': 'Manat do Azerbaijão', 'cod': 'AZN', 'number': '944', 'symbol': 'AZN$'},
    'BSD': {'country': 'BAHAMAS (THE)', 'currency': 'Dólar das Bahamas', 'cod': 'BSD', 'number': '044', 'symbol': 'BSD$'},
    'BHD': {'country': 'BAHREIN', 'currency': 'Dinar do Bahrein', 'cod': 'BHD', 'number': '048', 'symbol': 'BHD$'},
    'BDT': {'country': 'BANGLADESH', 'currency': 'Taka', 'cod': 'BDT', 'number': '050', 'symbol': 'BDT$'},
    'BBD': {'country': 'BARBADOS', 'currency': 'Dólar de Barbados', 'cod': 'BBD', 'number': '052', 'symbol': 'BBD$'},
    'BYR': {'country': 'BELARUS', 'currency': 'Rublo bielorrusso', 'cod': 'BYR', 'number': '974', 'symbol': 'BYR$'},
    'EUR': {'country': 'BÉLGICA', 'currency': 'Euro', 'cod': 'EUR', 'number': '978', 'symbol': 'EUR$'},
    'BZD': {'country': 'BELIZE', 'currency': 'Dólar de Belize', 'cod': 'BZD', 'number': '084', 'symbol': 'BZD$'},
    'XOF': {'country': 'BENIN', 'currency': 'CFA Franco BCEAO', 'cod': 'XOF', 'number': '952', 'symbol': 'XOF$'},
    'BMD': {'country': 'BERMUDA', 'currency': 'Dólar das Bermudas', 'cod': 'BMD', 'number': '060', 'symbol': 'BMD$'},
    'BTN': {'country': 'Butão', 'currency': 'Ngultrum', 'cod': 'BTN', 'number': '064', 'symbol': 'BTN$'},
    'INR': {'country': 'Butão', 'currency': 'Rupia indiana', 'cod': 'INR', 'number': '356', 'symbol': 'INR$'},
    'BOB': {'country': 'BOLÍVIA (ESTADO PLURINACIONAL    DA)', 'currency': 'Boliviano', 'cod': 'BOB', 'number': '068', 'symbol': 'BOB$'},
    'BOV': {'country': 'BOLÍVIA (ESTADO PLURINACIONAL  DA)', 'currency': 'Mvdol', 'cod': 'BOV', 'number': '984', 'symbol': 'BOV$'},
    # 'USD':{'country':'BONAIRE, SINT EUSTATIUS E SABA','currency':'Dólar americano','cod':'USD','number':'840','symbol':'USD$'},
    'BAM': {'country': 'BOSNIA E HERZEGOVINA', 'currency': 'Marco conversível', 'cod': 'BAM', 'number': '977', 'symbol': 'BAM$'},
    'BWP': {'country': 'BOTSWANA', 'currency': 'Pula', 'cod': 'BWP', 'number': '072', 'symbol': 'BWP$'},
    'NOK': {'country': 'ILHA DE BOUVET', 'currency': 'Coroa norueguesa', 'cod': 'NOK', 'number': '578', 'symbol': 'NOK$'},
    'BRL': {'country': 'BRASIL', 'currency': 'Real brasileiro', 'cod': 'BRL', 'number': '986', 'symbol': 'R$'},
    # 'USD':{'country':'TERRITÓRIO OCEANO BRITÂNICO (THE)','currency':'Dólar americano','cod':'USD','number':'840','symbol':'USD$'},
    'BND': {'country': 'BRUNEI DARUSSALAM', 'currency': 'Dólares de Brunei', 'cod': 'BND', 'number': '096', 'symbol': 'BND$'},
    'BGN': {'country': 'BULGÁRIA', 'currency': 'Lev búlgaro', 'cod': 'BGN', 'number': '975', 'symbol': 'BGN$'},
    'XOF': {'country': 'BURKINA FASO', 'currency': 'CFA Franco BCEAO', 'cod': 'XOF', 'number': '952', 'symbol': 'XOF$'},
    'BIF': {'country': 'BURUNDI', 'currency': 'Franco do Burundi', 'cod': 'BIF', 'number': '108', 'symbol': 'BIF$'},
    'CVE': {'country': 'CABO VERDE', 'currency': 'Cabo Verde Escudo', 'cod': 'CVE', 'number': '132', 'symbol': 'CVE$'},
    'KHR': {'country': 'CAMBODIA', 'currency': 'Riel', 'cod': 'KHR', 'number': '116', 'symbol': 'KHR$'},
    'XAF': {'country': 'CAMARÕES', 'currency': 'CFA Franc BEAC', 'cod': 'XAF', 'number': '950', 'symbol': 'XAF$'},
    'CAD': {'country': 'CANADÁ', 'currency': 'Dólar canadense', 'cod': 'CAD', 'number': '124', 'symbol': 'CAD$'},
    'KYD': {'country': 'ILHAS CAYMAN', 'currency': 'Dólar das Ilhas Caimã', 'cod': 'KYD', 'number': '136', 'symbol': 'KYD$'},
    'XAF': {'country': 'REPÚBLICA CENTRO-AFRICANA', 'currency': 'CFA Franc BEAC', 'cod': 'XAF', 'number': '950', 'symbol': 'XAF$'},
    'XAF': {'country': 'CHAD', 'currency': 'CFA Franc BEAC', 'cod': 'XAF', 'number': '950', 'symbol': 'XAF$'},
    'CLF': {'country': 'CHILE', 'currency': 'Unidad de Fomento', 'cod': 'CLF', 'number': '990', 'symbol': 'CLF$'},
    'CLP': {'country': 'CHILE', 'currency': 'Peso chileno', 'cod': 'CLP', 'number': '152', 'symbol': 'CLP$'},
    'CNY': {'country': 'CHINA', 'currency': 'Yuan Renminbi', 'cod': 'CNY', 'number': '156', 'symbol': 'CNY$'},
    'AUD': {'country': 'ILHA DO NATAL', 'currency': 'Dólar australiano', 'cod': 'AUD', 'number': '036', 'symbol': 'AUD$'},
    'AUD': {'country': 'ILHAS COCOS', 'currency': 'Dólar australiano', 'cod': 'AUD', 'number': '036', 'symbol': 'AUD$'},
    'COP': {'country': 'COLÔMBIA', 'currency': 'Peso colombiano', 'cod': 'COP', 'number': '170', 'symbol': 'COP$'},
    'COU': {'country': 'COLÔMBIA', 'currency': 'Unidade de Valor Real', 'cod': 'COU', 'number': '970', 'symbol': 'COU$'},
    'KMF': {'country': 'COMOROS', 'currency': 'Franco Comor', 'cod': 'KMF', 'number': '174', 'symbol': 'KMF$'},
    'CDF': {'country': 'CONGO (REPÚBLICA DEMOCRÁTICA DO)', 'currency': 'Fran congolesac', 'cod': 'CDF', 'number': '976', 'symbol': 'CDF$'},
    'XAF': {'country': 'CONGO', 'currency': 'CFA Franc BEAC', 'cod': 'XAF', 'number': '950', 'symbol': 'XAF$'},
    'NZD': {'country': 'ILHAS COOK', 'currency': 'Dólar da Nova Zelândia', 'cod': 'NZD', 'number': '554', 'symbol': 'NZD$'},
    'CRC': {'country': 'COSTA RICA', 'currency': 'Colon da Costa Rica', 'cod': 'CRC', 'number': '188', 'symbol': 'CRC$'},
    'XOF': {'country': 'COSTA DO MARFIM', 'currency': 'CFA Franc BCEAO', 'cod': 'XOF', 'number': '952', 'symbol': 'XOF$'},
    'HRK': {'country': 'CROÁCIA', 'currency': 'Kuna', 'cod': 'HRK', 'number': '191', 'symbol': 'HRK$'},
    'CUC': {'country': 'CUBA', 'currency': 'Peso conversível', 'cod': 'CUC', 'number': '931', 'symbol': 'CUC$'},
    'CUP': {'country': 'CUBA', 'currency': 'Peso cubano', 'cod': 'CUP', 'number': '192', 'symbol': 'CUP$'},
    'ANG': {'country': 'CURAÇAO', 'currency': 'Guilder das Antilhas Holandesas', 'cod': 'ANG', 'number': '532', 'symbol': 'ANG$'},
    'EUR': {'country': 'CHIPRE', 'currency': 'Euro', 'cod': 'EUR', 'number': '978', 'symbol': 'EUR$'},
    'CZK': {'country': 'REPÚBLICA CHECA', 'currency': 'Coroa Tcheca', 'cod': 'CZK', 'number': '203', 'symbol': 'CZK$'},
    'DKK': {'country': 'DINAMARCA', 'currency': 'Coroa dinamarquesa', 'cod': 'DKK', 'number': '208', 'symbol': 'DKK$'},
    'DJF': {'country': 'DJIBOUTI', 'currency': 'Franco do Djibouti', 'cod': 'DJF', 'number': '262', 'symbol': 'DJF$'},
    'XCD': {'country': 'DOMINICA', 'currency': 'Dólar do Caribe Oriental', 'cod': 'XCD', 'number': '951', 'symbol': 'XCD$'},
    'DOP': {'country': 'REPÚBLICA DOMINICANA', 'currency': 'Peso dominicano', 'cod': 'DOP', 'number': '214', 'symbol': 'DOP$'},
    # 'USD':{'country':'EQUADOR','currency':'Dólar americano','cod':'USD','number':'840','symbol':'USD$'},
    'EGP': {'country': 'EGITO', 'currency': 'Libra egípcia', 'cod': 'EGP', 'number': '818', 'symbol': 'EGP$'},
    'SVC': {'country': 'EL SALVADOR', 'currency': 'Cólon de El Salvador', 'cod': 'SVC', 'number': '222', 'symbol': 'SVC$'},
    # 'USD':{'country':'EL SALVADOR','currency':'Dólar americano','cod':'USD','number':'840','symbol':'USD$'},
    'XAF': {'country': 'GUINÉ EQUATORIAL', 'currency': 'CFA Franc BEAC', 'cod': 'XAF', 'number': '950', 'symbol': 'XAF$'},
    'ERN': {'country': 'ERITREA', 'currency': 'Nakfa', 'cod': 'ERN', 'number': '232', 'symbol': 'ERN$'},
    'EUR': {'country': 'ESTÔNIA', 'currency': 'Euro', 'cod': 'EUR', 'number': '978', 'symbol': 'EUR$'},
    'ETB': {'country': 'ETIÓPIA', 'currency': 'Birr etíope', 'cod': 'ETB', 'number': '230', 'symbol': 'ETB$'},
    'EUR': {'country': 'UNIÃO EUROPÉIA', 'currency': 'Euro', 'cod': 'EUR', 'number': '978', 'symbol': 'EUR$'},
    'FKP': {'country': 'ILHAS FALKLAND    [MALVINAS]', 'currency': 'Libra das Ilhas Falkland', 'cod': 'FKP', 'number': '238', 'symbol': 'FKP$'},
    'DKK': {'country': 'ILHAS FAROE', 'currency': 'Coroa dinamarquesa', 'cod': 'DKK', 'number': '208', 'symbol': 'DKK$'},
    'FJD': {'country': 'FIJI', 'currency': 'Dólar de Fiji', 'cod': 'FJD', 'number': '242', 'symbol': 'FJD$'},
    'EUR': {'country': 'FINLÂNDIA', 'currency': 'Euro', 'cod': 'EUR', 'number': '978', 'symbol': 'EUR$'},
    'EUR': {'country': 'FRANÇA', 'currency': 'Euro', 'cod': 'EUR', 'number': '978', 'symbol': 'EUR$'},
    'EUR': {'country': 'GUIANA FRANCESA', 'currency': 'Euro', 'cod': 'EUR', 'number': '978', 'symbol': 'EUR$'},
    'XPF': {'country': 'POLINÉSIA FRANCESA', 'currency': 'CFP Franc', 'cod': 'XPF', 'number': '953', 'symbol': 'XPF$'},
    'EUR': {'country': 'TERRITÓRIOS DO SUL FRANCÊS', 'currency': 'Euro', 'cod': 'EUR', 'number': '978', 'symbol': 'EUR$'},
    'XAF': {'country': 'GABÃO', 'currency': 'CFA Franc BEAC', 'cod': 'XAF', 'number': '950', 'symbol': 'XAF$'},
    'GMD': {'country': 'GÂMBIA', 'currency': 'Dalasi', 'cod': 'GMD', 'number': '270', 'symbol': 'GMD$'},
    'GEL': {'country': 'GEÓRGIA', 'currency': 'Lari', 'cod': 'GEL', 'number': '981', 'symbol': 'GEL$'},
    'EUR': {'country': 'ALEMANHA', 'currency': 'Euro', 'cod': 'EUR', 'number': '978', 'symbol': 'EUR$'},
    'GHS': {'country': 'GANA', 'currency': 'Ghana Cedi', 'cod': 'GHS', 'number': '936', 'symbol': 'GHS$'},
    'GIP': {'country': 'GIBRALTAR', 'currency': 'Libra De Gibraltar', 'cod': 'GIP', 'number': '292', 'symbol': 'GIP$'},
    'EUR': {'country': 'GRÉCIA', 'currency': 'Euro', 'cod': 'EUR', 'number': '978', 'symbol': 'EUR$'},
    'DKK': {'country': 'GRONELÂNDIA', 'currency': 'Coroa dinamarquesa', 'cod': 'DKK', 'number': '208', 'symbol': 'DKK$'},
    'XCD': {'country': 'GRENADA', 'currency': 'Dólar do Caribe Oriental', 'cod': 'XCD', 'number': '951', 'symbol': 'XCD$'},
    'EUR': {'country': 'GUADALUPE', 'currency': 'Euro', 'cod': 'EUR', 'number': '978', 'symbol': 'EUR$'},
    # 'USD':{'country':'GUAM','currency':'Dólar americano','cod':'USD','number':'840','symbol':'USD$'},
    'GTQ': {'country': 'GUATEMALA', 'currency': 'Quetzal', 'cod': 'GTQ', 'number': '320', 'symbol': 'GTQ$'},
    'GBP': {'country': 'GUERNSEY', 'currency': 'Libra esterlina', 'cod': 'GBP', 'number': '826', 'symbol': 'GBP$'},
    'GNF': {'country': 'GUINÉ', 'currency': 'Franco da Guiné', 'cod': 'GNF', 'number': '324', 'symbol': 'GNF$'},
    'XOF': {'country': 'GUINÉ-BISSAU', 'currency': 'CFA Franc BCEAO', 'cod': 'XOF', 'number': '952', 'symbol': 'XOF$'},
    'GYD': {'country': 'GUIANA', 'currency': 'Dólar da Guiana', 'cod': 'GYD', 'number': '328', 'symbol': 'GYD$'},
    'HTG': {'country': 'HAITI', 'currency': 'Gourde', 'cod': 'HTG', 'number': '332', 'symbol': 'HTG$'},
    # 'USD':{'country':'HAITI','currency':'Dólar americano','cod':'USD','number':'840','symbol':'USD$'},
    'AUD': {'country': 'ILHAS HEARD E ILHAS McDONALD', 'currency': 'Dólar australiano', 'cod': 'AUD', 'number': '036', 'symbol': 'AUD$'},
    'EUR': {'country': 'MAR SANTO', 'currency': 'Euro', 'cod': 'EUR', 'number': '978', 'symbol': 'EUR$'},
    'HNL': {'country': 'HONDURAS', 'currency': 'Lempira', 'cod': 'HNL', 'number': '340', 'symbol': 'HNL$'},
    'HKD': {'country': 'HONG KONG', 'currency': 'Dólar de Hong Kong', 'cod': 'HKD', 'number': '344', 'symbol': 'HKD$'},
    'HUF': {'country': 'HUNGRIA', 'currency': 'Forint', 'cod': 'HUF', 'number': '348', 'symbol': 'HUF$'},
    'ISK': {'country': 'ISLÂNDIA', 'currency': 'Coroa da Islândia', 'cod': 'ISK', 'number': '352', 'symbol': 'ISK$'},
    'INR': {'country': 'ÍNDIA', 'currency': 'Rupia indiana', 'cod': 'INR', 'number': '356', 'symbol': 'INR$'},
    'IDR': {'country': 'INDONÉSIA', 'currency': 'Rupia', 'cod': 'IDR', 'number': '360', 'symbol': 'IDR$'},
    'XDR': {'country': 'FUNDO MONETÁRIO INTERNACIONAL (IMF)', 'currency': 'SDR (Special Drawing Right)', 'cod': 'XDR', 'number': '960', 'symbol': 'XDR$'},
    'IRR': {'country': 'IRÃ (REPÚBLICA ISLÂMICA DO)', 'currency': 'Rial iraniano', 'cod': 'IRR', 'number': '364', 'symbol': 'IRR$'},
    'IQD': {'country': 'IRAQUE', 'currency': 'Dinar iraquiano', 'cod': 'IQD', 'number': '368', 'symbol': 'IQD$'},
    'EUR': {'country': 'IRLANDA', 'currency': 'Euro', 'cod': 'EUR', 'number': '978', 'symbol': 'EUR$'},
    'GBP': {'country': 'ILHA DE MAN', 'currency': 'Libra esterlina', 'cod': 'GBP', 'number': '826', 'symbol': 'GBP$'},
    'ILS': {'country': 'ISRAEL', 'currency': 'Novo Sheqel israelense', 'cod': 'ILS', 'number': '376', 'symbol': 'ILS$'},
    'EUR': {'country': 'ITÁLIA', 'currency': 'Euro', 'cod': 'EUR', 'number': '978', 'symbol': 'EUR$'},
    'JMD': {'country': 'JAMAICA', 'currency': 'Dólar jamaicano', 'cod': 'JMD', 'number': '388', 'symbol': 'JMD$'},
    'JPY': {'country': 'JAPÃO', 'currency': 'Iene', 'cod': 'JPY', 'number': '392', 'symbol': 'JPY$'},
    'GBP': {'country': 'JERSEY', 'currency': 'Libra esterlina', 'cod': 'GBP', 'number': '826', 'symbol': 'GBP$'},
    'JOD': {'country': 'JORDÂNIA', 'currency': 'Dinar jordaniano', 'cod': 'JOD', 'number': '400', 'symbol': 'JOD$'},
    'KZT': {'country': 'CAZAQUISTÃO', 'currency': 'Tenge', 'cod': 'KZT', 'number': '398', 'symbol': 'KZT$'},
    'KES': {'country': 'QUÊNIA', 'currency': 'Xelim do Quênia', 'cod': 'KES', 'number': '404', 'symbol': 'KES$'},
    'AUD': {'country': 'KIRIBATI', 'currency': 'Dólar australiano', 'cod': 'AUD', 'number': '036', 'symbol': 'AUD$'},
    'KPW': {'country': 'CORÉIA (REPÚLICA POPULAR)', 'currency': 'Won norte-coreano', 'cod': 'KPW', 'number': '408', 'symbol': 'KPW$'},
    'KRW': {'country': 'CORÉIA (REPÚBLICA DA)', 'currency': 'Won', 'cod': 'KRW', 'number': '410', 'symbol': 'KRW$'},
    'KWD': {'country': 'KUWAIT', 'currency': 'O Dinar do Kuwait', 'cod': 'KWD', 'number': '414', 'symbol': 'KWD$'},
    'KGS': {'country': 'QUIRGUIZISTÃO', 'currency': 'Som', 'cod': 'KGS', 'number': '417', 'symbol': 'KGS$'},
    'LAK': {'country': 'LAO', 'currency': 'Kip', 'cod': 'LAK', 'number': '418', 'symbol': 'LAK$'},
    'EUR': {'country': 'LETÔNIA', 'currency': 'Euro', 'cod': 'EUR', 'number': '978', 'symbol': 'EUR$'},
    'LBP': {'country': 'LÍBANO', 'currency': 'Libra libanesa', 'cod': 'LBP', 'number': '422', 'symbol': 'LBP$'},
    'LSL': {'country': 'LESOTHO', 'currency': 'Loti', 'cod': 'LSL', 'number': '426', 'symbol': 'LSL$'},
    'ZAR': {'country': 'LESOTHO', 'currency': 'Rand', 'cod': 'ZAR', 'number': '710', 'symbol': 'ZAR$'},
    'LRD': {'country': 'LIBÉRIA', 'currency': 'Dólar liberiano', 'cod': 'LRD', 'number': '430', 'symbol': 'LRD$'},
    'LYD': {'country': 'LÍBIA', 'currency': 'Dinar da Líbia', 'cod': 'LYD', 'number': '434', 'symbol': 'LYD$'},
    'CHF': {'country': 'LIECHTENSTEIN', 'currency': 'Franco suíço', 'cod': 'CHF', 'number': '756', 'symbol': 'CHF$'},
    'EUR': {'country': 'LITUÂNIA', 'currency': 'Euro', 'cod': 'EUR', 'number': '978', 'symbol': 'EUR$'},
    'EUR': {'country': 'LUXEMBURGO', 'currency': 'Euro', 'cod': 'EUR', 'number': '978', 'symbol': 'EUR$'},
    'MOP': {'country': 'MACAO', 'currency': 'Pataca', 'cod': 'MOP', 'number': '446', 'symbol': 'MOP$'},
    'MKD': {'country': 'MACEDÔNIA (ANTIGA REPÚBLICA JUGOSLAVA)', 'currency': 'Denar', 'cod': 'MKD', 'number': '807', 'symbol': 'MKD$'},
    'MGA': {'country': 'MADAGASCAR', 'currency': 'Ariary malgaxe', 'cod': 'MGA', 'number': '969', 'symbol': 'MGA$'},
    'MWK': {'country': 'MALAWI', 'currency': 'Kwacha', 'cod': 'MWK', 'number': '454', 'symbol': 'MWK$'},
    'MYR': {'country': 'MALÁSIA', 'currency': 'Ringgit da Malásia', 'cod': 'MYR', 'number': '458', 'symbol': 'MYR$'},
    'MVR': {'country': 'MALDIVAS', 'currency': 'Rufiyaa', 'cod': 'MVR', 'number': '462', 'symbol': 'MVR$'},
    'XOF': {'country': 'MALI', 'currency': 'CFA Franc BCEAO', 'cod': 'XOF', 'number': '952', 'symbol': 'XOF$'},
    'EUR': {'country': 'MALTA', 'currency': 'Euro', 'cod': 'EUR', 'number': '978', 'symbol': 'EUR$'},
    # 'USD':{'country':'ILHAS MARSHALL','currency':'Dólar americano','cod':'USD','number':'840','symbol':'USD$'},
    'EUR': {'country': 'MARTINICA', 'currency': 'Euro', 'cod': 'EUR', 'number': '978', 'symbol': 'EUR$'},
    'MRO': {'country': 'MAURITÂNIA', 'currency': 'Ouguiya', 'cod': 'MRO', 'number': '478', 'symbol': 'MRO$'},
    'MUR': {'country': 'MAURÍCIA', 'currency': 'Rupia das Maurícias', 'cod': 'MUR', 'number': '480', 'symbol': 'MUR$'},
    'EUR': {'country': 'MAYOTTE', 'currency': 'Euro', 'cod': 'EUR', 'number': '978', 'symbol': 'EUR$'},
    'XUA': {'country': 'PAÍSES MEMBROS DO GRUPO DO BANCO AFRICANO DE DESENVOLVIMENTO', 'currency': 'Unidade de Conta do ADB', 'cod': 'XUA', 'number': '965', 'symbol': 'XUA$'},
    'MXN': {'country': 'MÉXICO', 'currency': 'Peso mexicano', 'cod': 'MXN', 'number': '484', 'symbol': 'MXN$'},
    'MXV': {'country': 'MÉXICO', 'currency': 'Unidade de Investimento Mexicana (UDI)', 'cod': 'MXV', 'number': '979', 'symbol': 'MXV$'},
    # 'USD':{'country':'MICRONÉSIA (ESTADOS FEDERADOS DA)','currency':'Dólar americano','cod':'USD','number':'840','symbol':'USD$'},
    'MDL': {'country': 'MOLDÁVIA', 'currency': 'Leão da Moldávia', 'cod': 'MDL', 'number': '498', 'symbol': 'MDL$'},
    'EUR': {'country': 'MÓNACO', 'currency': 'Euro', 'cod': 'EUR', 'number': '978', 'symbol': 'EUR$'},
    'MNT': {'country': 'MONGÓLIA', 'currency': 'Tugrik', 'cod': 'MNT', 'number': '496', 'symbol': 'MNT$'},
    'EUR': {'country': 'MONTENEGRO', 'currency': 'Euro', 'cod': 'EUR', 'number': '978', 'symbol': 'EUR$'},
    'XCD': {'country': 'MONTSERRAT', 'currency': 'Dólar do Caribe Oriental', 'cod': 'XCD', 'number': '951', 'symbol': 'XCD$'},
    'MAD': {'country': 'MARROCOS', 'currency': 'Dirham marroquino', 'cod': 'MAD', 'number': '504', 'symbol': 'MAD$'},
    'MZN': {'country': 'MOÇAMBIQUE', 'currency': 'Moçambique Metical', 'cod': 'MZN', 'number': '943', 'symbol': 'MZN$'},
    'MMK': {'country': 'MYANMAR', 'currency': 'Kyat', 'cod': 'MMK', 'number': '104', 'symbol': 'MMK$'},
    'NAD': {'country': 'NAMÍBIA', 'currency': 'Dólares da Namíbia', 'cod': 'NAD', 'number': '516', 'symbol': 'NAD$'},
    'ZAR': {'country': 'NAMÍBIA', 'currency': 'Rand', 'cod': 'ZAR', 'number': '710', 'symbol': 'ZAR$'},
    'AUD': {'country': 'NAURU', 'currency': 'Dólar australiano', 'cod': 'AUD', 'number': '036', 'symbol': 'AUD$'},
    'NPR': {'country': 'NEPAL', 'currency': 'Rupia nepalesa', 'cod': 'NPR', 'number': '524', 'symbol': 'NPR$'},
    'EUR': {'country': 'PAÍSES BAIXOS', 'currency': 'Euro', 'cod': 'EUR', 'number': '978', 'symbol': 'EUR$'},
    'XPF': {'country': 'NOVA CALEDÔNIA', 'currency': 'CFP Franc', 'cod': 'XPF', 'number': '953', 'symbol': 'XPF$'},
    'NZD': {'country': 'NOVA ZELÂNDIA', 'currency': 'Dólar da Nova Zelândia', 'cod': 'NZD', 'number': '554', 'symbol': 'NZD$'},
    'NIO': {'country': 'NICARÁGUA', 'currency': 'Cordoba Oro', 'cod': 'NIO', 'number': '558', 'symbol': 'NIO$'},
    'XOF': {'country': 'NÍGER', 'currency': 'CFA Franc BCEAO', 'cod': 'XOF', 'number': '952', 'symbol': 'XOF$'},
    'NGN': {'country': 'NIGÉRIA', 'currency': 'Naira', 'cod': 'NGN', 'number': '566', 'symbol': 'NGN$'},
    'NZD': {'country': 'NIUE', 'currency': 'Dólar da Nova Zelândia', 'cod': 'NZD', 'number': '554', 'symbol': 'NZD$'},
    'AUD': {'country': 'ILHA NORFOLK', 'currency': 'Dólar australiano', 'cod': 'AUD', 'number': '036', 'symbol': 'AUD$'},
    # 'USD':{'country':'ILHAS MARIANAS DO NORTE','currency':'Dólar americano','cod':'USD','number':'840','symbol':'USD$'},
    'NOK': {'country': 'NORUEGA', 'currency': 'Coroa norueguesa', 'cod': 'NOK', 'number': '578', 'symbol': 'NOK$'},
    'OMR': {'country': 'OMAN', 'currency': 'Rial Omani', 'cod': 'OMR', 'number': '512', 'symbol': 'OMR$'},
    'PKR': {'country': 'PAQUISTÃO', 'currency': 'Rupia do Paquistão', 'cod': 'PKR', 'number': '586', 'symbol': 'PKR$'},
    # 'USD':{'country':'PALAU','currency':'Dólar americano','cod':'USD','number':'840','symbol':'USD$'},
    'PAB': {'country': 'PANAMÁ', 'currency': 'Balboa', 'cod': 'PAB', 'number': '590', 'symbol': 'PAB$'},
    # 'USD':{'country':'PANAMÁ','currency':'Dólar americano','cod':'USD','number':'840','symbol':'USD$'},
    'PGK': {'country': 'PAPUA NOVA GUINÉ', 'currency': 'Kina', 'cod': 'PGK', 'number': '598', 'symbol': 'PGK$'},
    'PYG': {'country': 'PARAGUAI', 'currency': 'Guarani', 'cod': 'PYG', 'number': '600', 'symbol': 'PYG$'},
    'PEN': {'country': 'PERU', 'currency': 'Nuevo Sol', 'cod': 'PEN', 'number': '604', 'symbol': 'PEN$'},
    'PHP': {'country': 'FILIPINAS', 'currency': 'Peso filipino', 'cod': 'PHP', 'number': '608', 'symbol': 'PHP$'},
    'NZD': {'country': 'PITCAIRN', 'currency': 'Dólar da Nova Zelândia', 'cod': 'NZD', 'number': '554', 'symbol': 'NZD$'},
    'PLN': {'country': 'POLÔNIA', 'currency': 'Zloty', 'cod': 'PLN', 'number': '985', 'symbol': 'PLN$'},
    'EUR': {'country': 'PORTUGAL', 'currency': 'Euro', 'cod': 'EUR', 'number': '978', 'symbol': 'EUR$'},
    # 'USD':{'country':'PUERTO RICO','currency':'Dólar americano','cod':'USD','number':'840','symbol':'USD$'},
    'QAR': {'country': 'QATAR', 'currency': 'Qatari Rial', 'cod': 'QAR', 'number': '634', 'symbol': 'QAR$'},
    'EUR': {'country': 'RÉUNION', 'currency': 'Euro', 'cod': 'EUR', 'number': '978', 'symbol': 'EUR$'},
    'RON': {'country': 'ROMÊNIA', 'currency': 'Leu romeno', 'cod': 'RON', 'number': '946', 'symbol': 'RON$'},
    'RUB': {'country': 'FEDERAÇÃO RUSSA', 'currency': 'rublo russo', 'cod': 'RUB', 'number': '643', 'symbol': 'RUB$'},
    'RWF': {'country': 'RWANDA', 'currency': 'Rwanda Franc', 'cod': 'RWF', 'number': '646', 'symbol': 'RWF$'},
    'EUR': {'country': 'SAINT BARTHÉLEMY', 'currency': 'Euro', 'cod': 'EUR', 'number': '978', 'symbol': 'EUR$'},
    'SHP': {'country': 'SAINT HELENA, ASCENSION E TRISTAN DA CUNHA', 'currency': 'Saint Helena Pound', 'cod': 'SHP', 'number': '654', 'symbol': 'SHP$'},
    'XCD': {'country': 'SAINT KITTS E NEVIS', 'currency': 'Dólar do Caribe Oriental', 'cod': 'XCD', 'number': '951', 'symbol': 'XCD$'},
    'XCD': {'country': 'SAINT LUCIA', 'currency': 'Dólar do Caribe Oriental', 'cod': 'XCD', 'number': '951', 'symbol': 'XCD$'},
    'EUR': {'country': 'SÃO MARTINHO (PARTE FRANCESA)', 'currency': 'Euro', 'cod': 'EUR', 'number': '978', 'symbol': 'EUR$'},
    'EUR': {'country': 'SÃO PIERRE E MIQUELON', 'currency': 'Euro', 'cod': 'EUR', 'number': '978', 'symbol': 'EUR$'},
    'XCD': {'country': 'SÃO VICENTE E GRENADINES', 'currency': 'Dólar do Caribe Oriental', 'cod': 'XCD', 'number': '951', 'symbol': 'XCD$'},
    'WST': {'country': 'SAMOA', 'currency': 'Tala', 'cod': 'WST', 'number': '882', 'symbol': 'WST$'},
    'EUR': {'country': 'SAN MARINO', 'currency': 'Euro', 'cod': 'EUR', 'number': '978', 'symbol': 'EUR$'},
    'STD': {'country': 'SÃO TOMÉ E PRÍNCIPE', 'currency': 'Dobra', 'cod': 'STD', 'number': '678', 'symbol': 'STD$'},
    'SAR': {'country': 'ARÁBIA SAUDITA', 'currency': 'Rial saudita', 'cod': 'SAR', 'number': '682', 'symbol': 'SAR$'},
    'XOF': {'country': 'SENEGAL', 'currency': 'CFA Franc BCEAO', 'cod': 'XOF', 'number': '952', 'symbol': 'XOF$'},
    'RSD': {'country': 'SÉRVIA', 'currency': 'Dinar sérvio', 'cod': 'RSD', 'number': '941', 'symbol': 'RSD$'},
    'SCR': {'country': 'SEYCHELLES', 'currency': 'Rúpia das Seychelles', 'cod': 'SCR', 'number': '690', 'symbol': 'SCR$'},
    'SLL': {'country': 'SERRA LEOA', 'currency': 'Leone', 'cod': 'SLL', 'number': '694', 'symbol': 'SLL$'},
    'SGD': {'country': 'CINGAPURA', 'currency': 'Dólar de Singapura', 'cod': 'SGD', 'number': '702', 'symbol': 'SGD$'},
    'ANG': {'country': 'SINT MAARTEN (PARTE INGLESA)', 'currency': 'Guilder das Antilhas Holandesas', 'cod': 'ANG', 'number': '532', 'symbol': 'ANG$'},
    'XSU': {'country': 'SISTEMA UNITARIO DE COMPENSACION REGIONAL DE PAGOS \'SUCRE', 'currency': 'Sucre', 'cod': 'XSU', 'number': '994', 'symbol': 'XSU$'},
    'EUR': {'country': 'ESLOVÁQUIA', 'currency': 'Euro', 'cod': 'EUR', 'number': '978', 'symbol': 'EUR$'},
    'EUR': {'country': 'ESLOVÉNIA', 'currency': 'Euro', 'cod': 'EUR', 'number': '978', 'symbol': 'EUR$'},
    'SBD': {'country': 'ILHAS SALOMÃO', 'currency': 'Dólar das Ilhas Salomão', 'cod': 'SBD', 'number': '090', 'symbol': 'SBD$'},
    'SOS': {'country': 'SOMÁLIA', 'currency': 'Shilling Somali', 'cod': 'SOS', 'number': '706', 'symbol': 'SOS$'},
    'ZAR': {'country': 'ÁFRICA DO SUL', 'currency': 'Rand', 'cod': 'ZAR', 'number': '710', 'symbol': 'ZAR$'},
    'SSP': {'country': 'SUDÃO DO SUL', 'currency': 'Libra Sudanesa do Sul', 'cod': 'SSP', 'number': '728', 'symbol': 'SSP$'},
    'EUR': {'country': 'ESPANHA', 'currency': 'Euro', 'cod': 'EUR', 'number': '978', 'symbol': 'EUR$'},
    'LKR': {'country': 'SRI LANKA', 'currency': 'Rupia do Sri Lanka', 'cod': 'LKR', 'number': '144', 'symbol': 'LKR$'},
    'SDG': {'country': 'SUDÃO', 'currency': 'Libra sudanesa', 'cod': 'SDG', 'number': '938', 'symbol': 'SDG$'},
    'SRD': {'country': 'SURINAME', 'currency': 'Dólar do Suriname', 'cod': 'SRD', 'number': '968', 'symbol': 'SRD$'},
    'NOK': {'country': 'SVALBARD E JAN MAYEN', 'currency': 'Coroa norueguesa', 'cod': 'NOK', 'number': '578', 'symbol': 'NOK$'},
    'SZL': {'country': 'Suazilândia', 'currency': 'Lilangeni', 'cod': 'SZL', 'number': '748', 'symbol': 'SZL$'},
    'SEK': {'country': 'SUÉCIA', 'currency': 'Swedish Krona', 'cod': 'SEK', 'number': '752', 'symbol': 'SEK$'},
    'CHE': {'country': 'SUÍÇA', 'currency': 'WIR Euro', 'cod': 'CHE', 'number': '947', 'symbol': 'CHE$'},
    'CHF': {'country': 'SUÍÇA', 'currency': 'Franco suíço', 'cod': 'CHF', 'number': '756', 'symbol': 'CHF$'},
    'CHW': {'country': 'SUÍÇA', 'currency': 'WIR Franc', 'cod': 'CHW', 'number': '948', 'symbol': 'CHW$'},
    'SYP': {'country': 'REPÚBLICA ÁRABE DA SÍRIA', 'currency': 'Libra síria', 'cod': 'SYP', 'number': '760', 'symbol': 'SYP$'},
    'TWD': {'country': 'TAIWAN, PROVÍNCIA DA CHINA)', 'currency': 'Novo dólar de Taiwan', 'cod': 'TWD', 'number': '901', 'symbol': 'TWD$'},
    'TJS': {'country': 'TAJIQUISTÃO', 'currency': 'Somoni', 'cod': 'TJS', 'number': '972', 'symbol': 'TJS$'},
    'TZS': {'country': 'TANZÂNIA, REPÚBLICA UNIDA', 'currency': 'Xelim da Tanzânia', 'cod': 'TZS', 'number': '834', 'symbol': 'TZS$'},
    'THB': {'country': 'TAILÂNDIA', 'currency': 'Baht', 'cod': 'THB', 'number': '764', 'symbol': 'THB$'},
    # 'USD':{'country':'TIMOR-LESTE','currency':'Dólar americano','cod':'USD','number':'840','symbol':'USD$'},
    'XOF': {'country': 'TOGO', 'currency': 'CFA Franc BCEAO', 'cod': 'XOF', 'number': '952', 'symbol': 'XOF$'},
    'NZD': {'country': 'TOKELAU', 'currency': 'Dólar da Nova Zelândia', 'cod': 'NZD', 'number': '554', 'symbol': 'NZD$'},
    'TOP': {'country': 'TONGA', 'currency': 'Pa’anga', 'cod': 'TOP', 'number': '776', 'symbol': 'TOP$'},
    'TTD': {'country': 'TRINIDAD E TOBAGO', 'currency': 'Dólar de Trinidad e Tobago', 'cod': 'TTD', 'number': '780', 'symbol': 'TTD$'},
    'TND': {'country': 'TUNÍSIA', 'currency': 'Dinar tunisino', 'cod': 'TND', 'number': '788', 'symbol': 'TND$'},
    'TRY': {'country': 'TURQUIA', 'currency': 'Lira turca', 'cod': 'TRY', 'number': '949', 'symbol': 'TRY$'},
    'TMT': {'country': 'Turquemenistão', 'currency': 'Turcomenistão New Manat', 'cod': 'TMT', 'number': '934', 'symbol': 'TMT$'},
    # 'USD':{'country':'TURKS E CAICOS ISLANDS','currency':'Dólar americano','cod':'USD','number':'840','symbol':'USD$'},
    'AUD': {'country': 'TUVALU', 'currency': 'Dólar australiano', 'cod': 'AUD', 'number': '036', 'symbol': 'AUD$'},
    'UGX': {'country': 'UGANDA', 'currency': 'Xelim de Uganda', 'cod': 'UGX', 'number': '800', 'symbol': 'UGX$'},
    'UAH': {'country': 'UCRÂNIA', 'currency': 'Hryvnia', 'cod': 'UAH', 'number': '980', 'symbol': 'UAH$'},
    'AED': {'country': 'EMIRADOS ÁRABES UNIDOS', 'currency': 'UAE Dirham', 'cod': 'AED', 'number': '784', 'symbol': 'AED$'},
    'GBP': {'country': 'REINO UNIDO DA GRÃ-BRETANHA E IRLANDA DO NORTE', 'currency': 'Libra esterlina', 'cod': 'GBP', 'number': '826', 'symbol': 'GBP$'},
    # 'USD':{'country':'ILHAS OUTONARES MENORES DOS ESTADOS UNIDOS','currency':'Dólar americano','cod':'USD','number':'840','symbol':'USD$'},
    'USD': {'country': 'ESTADOS UNIDOS DA AMERICA', 'currency': 'Dólar americano', 'cod': 'USD', 'number': '840', 'symbol': 'US$'},
    'USN': {'country': 'ESTADOS UNIDOS DA AMERICA', 'currency': 'Dólar dos EUA (dia seguinte)', 'cod': 'USN', 'number': '997', 'symbol': 'USN$'},
    'UYI': {'country': 'URUGUAI', 'currency': 'Peso Uruguaio em Unidades Indexadas (URUIURUI)', 'cod': 'UYI', 'number': '940', 'symbol': 'UYI$'},
    'UYU': {'country': 'URUGUAI', 'currency': 'Peso Uruguaio', 'cod': 'UYU', 'number': '858', 'symbol': 'UYU$'},
    'UZS': {'country': 'Uzbequistão', 'currency': 'Soma do Uzbequistão', 'cod': 'UZS', 'number': '860', 'symbol': 'UZS$'},
    'VUV': {'country': 'VANUATU', 'currency': 'Vatu', 'cod': 'VUV', 'number': '548', 'symbol': 'VUV$'},
    'VEF': {'country': 'VENEZUELA (REPÚBLICA BOLIVARIANA DE)', 'currency': 'Bolívar', 'cod': 'VEF', 'number': '937', 'symbol': 'VEF$'},
    'VND': {'country': 'VIET NAM', 'currency': 'Dong', 'cod': 'VND', 'number': '704', 'symbol': 'VND$'},
    # 'USD':{'country':'ILHAS VIRGENS (BRITÂNICAS)','currency':'Dólar americano','cod':'USD','number':'840','symbol':'USD$'},
    # 'USD':{'country':'ILHAS VIRGENS (EUA)','currency':'Dólar americano','cod':'USD','number':'840','symbol':'USD$'},
    'XPF': {'country': 'WALLIS E FUTUNA', 'currency': 'CFP Franc', 'cod': 'XPF', 'number': '953', 'symbol': 'XPF$'},
    'MAD': {'country': 'SAARA OCIDENTAL', 'currency': 'Moroccan Dirham', 'cod': 'MAD', 'number': '504', 'symbol': 'MAD$'},
    'YER': {'country': 'IÉMEN', 'currency': 'Rial Iemenita', 'cod': 'YER', 'number': '886', 'symbol': 'YER$'},
    'ZMW': {'country': 'ZÂMBIA', 'currency': 'Zambian Kwacha', 'cod': 'ZMW', 'number': '967', 'symbol': 'ZMW$'},
    'ZWL': {'country': 'ZIMBÁBUE', 'currency': 'Dólar zimbabuano', 'cod': 'ZWL', 'number': '932', 'symbol': 'ZWL$'},
}


def cotacao(currencyFrom: str = 'USD', currencyTo: str = 'BRL'):
    global currencies
    url = f'https://economia.awesomeapi.com.br/last/{currencyFrom}-{currencyTo}'
    try:
        k = f'{currencyFrom}{currencyTo}'
        r = requests.get(url).json()[k]
        r['from'] = currencies[currencyFrom]
        r['to'] = currencies[currencyTo]
        return r
    except:
        ...

def getCurrencys():
    url = 'https://pt.wikipedia.org/wiki/ISO_4217'
    url = 'https://pt.iban.com/currency-codes'
    print(url)
    try:
        res = requests.get(url)
        # soup = BeautifulSoup(res.text)
    except:
        print('error URL')
        return

    # soup = BeautifulSoup(res.text, features='html.parser')
    soup = BeautifulSoup(res.text, features='lxml')

    # tracks = soup.find_all('a', attrs={'href': re.compile(r'\.mid$')}, string=re.compile(r'^((?!\().)*$'))
    # tbl=soup.find_all('table')

    trs = soup.select('div.flat-services table tr')
    next(trs)
    lines=[]
    for tr in trs:
        cells = tr.select('td')
        lines.append([tag for tag in cells])
